### ISSUE TITLE
Discuss license for Python: https://github.com/UBC-MDS/sanityze/issues/48

### ISSUE THREAD

**Issue by caesarw0** [UBC-MDS/sanityze#51]

**Comment by xXJohamXx** [comment]
We feel that the MIT license is acceptable to use for our package, taking into consideration the use case that it is intended for. We feel that eliminating personally identifiable information (PII) from data analysis is an essential part of safeguarding privacy, and we want to ensure that as many individuals as possible have access to this code. Therefore, we want the package to be widely used without restrictions. We also want to encourage others to adapt our package and contribute to it by adding capabilities to redact various sorts of personally identifiable information (PII). In addition, we explored utilizing many other kinds of open source licenses; nevertheless, the majority of them feature the same permissions but also come with an increased number of constraints. In general, we decided to go with the MIT license since it is brief, straightforward, and allows for the wider use that we desire while yet insulating us from legal responsibility and warranty issues.
